# This is a basic workflow that is manually triggered

name: Deploy

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
    types: [closed]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: pull-test-deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd e-commerce-project
          docker run -p 3307:3306 -e MYSQL_ROOT_PASSWORD=toor -e MYSQL_DATABASE=taktuku_project_test --name appDbTest -d mysql
          git pull origin main
          go test -v ./..
          docker-compose down && docker-compose up --build -d
